# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 390e4c414893a1842a27b2bacd904caa67a99b41e187fe8c086dd881a12d5441b16409a367a72b39ee14faada6b2dfde6a3948825569e3714c111a1b1d772d46

test:
  secret_key_base: f0bfe3ff8daac191de4dbb1745f670815edec08fff8334888035d5fe536abc38479c9dde55d447d32d55c9bf94258ff60a5893ce4c5c173fb0356e95607bc832

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
